### ISSUE TITLE
Replace StringLike class with String type

### ISSUE THREAD

**Issue by jamesdbrock** [markfarrell/purescript-parsing-hexadecimal#1]
Hi, in purescript-parsing v7.0.0 we deleted the `StringLike` typeclass.

https://github.com/purescript-contrib/purescript-parsing/releases/tag/v7.0.0

Because of that, I had to disable this package in package-sets.

https://github.com/purescript/package-sets/pull/1008

If you want to upgrade this package to purescript-parsing v7.0.0, it should suffice to delete all mentions of the `StringLike` typeclass and replace them with the `String` type.

**Comment by markfarrell** [comment]
Thanks @jamesdbrock.

https://github.com/purescript/package-sets/pull/1044
